# Generated by Django 5.1.6 on 2025-03-03 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='taraweeh',
            field=models.PositiveIntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8)], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ramadan_start_date',
            field=models.DateField(default=datetime.date(2025, 3, 2)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
