# Generated by Django 5.1.6 on 2025-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_activity_taraweeh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ramadan_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
